name: 'Global Build Numbers'
description: 'Manage global build numbers that can be used across projects'
inputs:
  OPERATION:
    description: 'Operation to perform: [increment | get | set]'
    required: true
    default: 'increment'
  DYNAMO_TABLE_NAME:
    description: 'Dynamo table name'
    required: false
    default: 'build-numbers'
  DYNAMO_PARTITION_KEY:
    description: 'Dynamo table partition key (must be type string)'
    required: false
    default: 'product-id'
  PRODUCT_ID:
    description: 'Arbitrary string to identify the number sequence'
    required: true
    default: 'build-number'
  CREATE_PRODUCT_ID:
    description: 'If product id not found then add it set build number to 0'
    required: false
    default: true
  VALUE:
    description: 'Value for set operations'
    required: false
    default: '0'
outputs:
  result:
    description: 'Result of the operation'
runs:
  using: 'node20'
  main: 'dist/index.js'
