name: Example workflow for Example Action

on: [push]

permissions:
  contents: read

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ohthepain/github-action-js-example@v1.2
      with:
        who-to-greet: 'Mona the Octocat'

